### ISSUE TITLE
okok Garage Compatibility

### ISSUE THREAD

**Issue by Arkosee** [MrNewb/MrNewbCustomPlates#2]
```
if Config.Keys ~= "ok" then return end
if Config.Debug then print("Keys Set To ", Config.Keys) end

function RemoveOldKeys(src, entityid, oldplate, newplate)
	TriggerClientEvent('okokGarage:removeKeys', src, oldplate)
	print('Removed keys for '.. oldplate)
end

function GiveKeys(src, entityid, oldplate, newplate)
	TriggerClientEvent("okokGarage:GiveKeys", newplate, src)
	print('Gave keys for '.. newplate)
end
```

Vehicles have to be unlocked **BEFORE** plate change is made, then stored and retrieved so it can be locked/unlocked like normal (I think it's got something to do with the way okok garage gives keys weirdly, even purchasing a car from a store you're required to store it before getting keys to it)

But none the less. it works with the above.. If yourself or someone else figures out a better way then let me know :)

**Comment by MrNewb** [comment]
I just looked at this, I've added this and credited you for the compatibility. (if you are in the discord check out the key system im working on, ive posted a video).
